server:
  port: 8080

spring:
  application:
    name: investment-tracker

  mongodb:
    uri: mongodb+srv://pthirumalayadav:pthirumalayadav@cluster0.x6trgen.mongodb.net/?retryWrites=true&w=majority
    database: Cluster0

app:
  security:
    key-secret: 80DC002A54B59ACF5F198D0A8D644EEE992C04FFBCF947DAAA90AA7DFDDA2A05
