server:
  port: 8080
spring:
  application:
    name: investment-tracker
  data:
    mongodb:
      uri: mongodb+srv://pthirumalayadav:g2sBWcz1MtxHi6wz@cluster0.x6trgen.mongodb.net/?retryWrites=true&w=majority
      database: Cluster0