openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0

components:
  schemas:
    FinanceRequest:
      type: object
      properties:
        calculationType:
          $ref: '#/components/schemas/CalculationType'
        principalAmount:
          type: number
          format: double
          default: 0
        rateOfInterest:
          description: Rate of interest per year (as percentage)
          type: number
          format: double
          default: 0
        timePeriod:
          description: Time period in months
          type: integer
          default: 0
        finalAmount:
          type: number
          format: double
          default: 0
        emiAmount:
          type: number
          format: double
          default: 0

    FinanceResponse:
      type: object
      properties:
        principalAmount:
          type: number
          format: double
        rateOfInterest:
          type: number
          format: double
        timePeriod:
          description: Time period in months
          type: number
          format: integer
        finalAmount:
          type: number
          format: double
        emiAmount:
          type: integer

    StepUpSIPRequest:
      type: object
      properties:
        initialAmount:
          type: number
          format: double
          default: 0
          description: The initial investment amount.
        stepUpRate:
          type: number
          format: double
          default: 0
          description: The rate at which the SIP amount increases per step-up period (e.g., 10%).
        stepUpFrequency:
          $ref: '#/components/schemas/StepUpFrequency'
          description: The frequency at which the SIP amount steps up.
        months:
          type: integer
          default: 0
          description: The total number of investment months.
        targetAmount:
          type: number
          default: 0
          format: double
          description: The desired target amount for the investment.

    InterestRateResponse:
      type: object
      writeOnly: true
      properties:
        monthlyRate:
          type: number
          format: double
          description: The monthly interest rate.
        annualRate:
          type: number
          format: double
          description: The annual interest rate.

    CalculationType:
      type: string
      enum:
        - EMI
        - TOTAL_AMOUNT
        - PRINCIPAL_AMOUNT
        - RATE_OF_INTEREST
        - TIME_PERIOD
        - NONE
      default: NONE

    StepUpFrequency:
      type: integer
      enum:
        - 1
        - 3
        - 6
        - 12
      x-enum-varnames:
        - MONTHLY
        - QUARTERLY
        - HALF_YEARLY
        - YEARLY
      default: 12
